/* Special thanks to Karel Pacovský <karelpacovsky@centrum.cz> for this translation. */

jquery_lang_js.prototype.lang.cs = {
	"DIPLOMATIC": "Diplomatická",
	"INTERPRETATIVE": "Interpretační",
	"CRITICAL": "Kritická",
	"TRANSLATION": "Překlad",
	"MODE_SINGLE_TEXT": "Pouze text",
	"MODE_IMAGE_TEXT": "Obraz a text",
	"MODE_TEXT_TEXT": "Text a text",
	"MODE_BOOKREADER": "Režim čtení",
	"PROJECT_INFO": "Informace o projektu",
	"OPTIONS": "Nastavení",
	"SETTINGS": "Nastavení",
	"LANGUAGES": "Jazyky",
	"ENGLISH": "Anglicky",
	"ITALIAN": "Italsky",
	"FRENCH": "Francouzsky",
	"GERMAN": "Německy",
	"CZECH": "Česky",
	"GO_FULLSCREEN": "Celá obrazovka",
	"EXIT_FULLSCREEN": "Ukončit režim celé obrazovky",
	"TOGGLE_MENU": "Zakrýt/zobrazit menu",
	"PREVIOUS_PAGE": "Předchozí strana",
	"NEXT_PAGE": "Další strana",
	"EXPAND_FRAME": "Zvětšit",
	"COLLAPSE_FRAME": "Zmenšit",
	"SELECTOR_PAGE": "Volba strany",
	"SELECTOR_DOUBLE_PAGE": "Volba dvojstrany",
	"THUMBNAILS": "Miniatury",
	"THUMBS": "Miniatury",
	"SELECTOR_EDITION_LEVEL": "Vybrat edici",
	"REGESTO": "Regest",
	"REGESTO_TITLE": "Zobrazit/skrýt regest",
	"INFORMATION_ABOUT_THIS_TEXT": "Informace o textu",
	"INFO": "Info",
	"MAGNIFIER_LENS": "Lupa",
	"MAGNIFIER": "Lupa",
	"HOT_SPOTS": "Aktivní místa na obrázku",
	"HOTSPOTS": "Hotspots",
	"IMAGE_TEXT_LINK": "Propojení obrazu a textu",
	"IMAGE_TEXT": "Obraz-text",
	"MANUSCRIPT_DESCRIPTION": "Popis rukopisu",
	"MS_DESC": "Popis",
	"TOGGLE_SEARCH": "Zvětšit/zmenšit hledání",
	"TOGGLE_KEYBOARD": "Zobrazit/skrýt klávesnici",
	"TOGGLE_CASE_SENSITIVE": "Povolit/zakázat malá a velká písmena vyhledávání",
	"CLEAR_SEARCH": "Nové hledání",
	"START_SEARCH": "Hledat",
	"ENTER_YOUR_QUERY_INTO_THE_SEARCH_BOX_ABOVE": "Zadejte hledaný text do rámečku",
	"OPEN_SEARCH": "Otevřít hledání",
	"SEARCH": "Hledat",
	"SELECTOR_ENTITIES": "Vybrat elementy",
	"NO_SELECTION": "Žádný výběr",
	"SELECT_ALL": "Vybrat vše",
	"CLEAR_SELECTION": "Zrušit výběr",
	"DECREASE_FONT_SIZE": "Zmenšit písmo",
	"INCREASE_FONT_SIZE": "Zvětšit písmo",
	"PREVIOUS_DOCUMENT": "Předchozí dokument",
	"NEXT_DOCUMENT": "Další dokument",
	"100%": "100%",
	"FIT_TO_FRAME": "Přizpůsobit velikost poli",
	"ZOOM_OUT": "Zmenšit",
	"ZOOM_IN": "Zvětšit",
	"NO_IMAGE": "Obrázek chybí",
	"EXPAND_FRAME": "Zvětšit na celou obrazovku",
	"SELECTOR_TEXT": "Vybrat text",
	"TOGGLE_LISTS": "Skrýt/zobrazit položky v seznamech",
	"OPEN_LISTS": "Zobrazit seznamy",
	"LISTS": "Seznamy",

	"EVT_INFORMATION": "Informace o EVT",
	"GENERAL_INFORMATION": "Obecné informace",
	"TITLE": "Název edice",
	"TEXT_AUTHOR": "Autor textu",
	"PRINCIPAL_INVESTIGATOR": "Hlavní koordinátor",
	"EDITION_STATEMENT": "Vydání vydání",
	"RESPONSIBILITY_STATEMENT": "Prohlášení o odpovědnosti",
	"PUBLICATION_INFORMATION": "Informace o publikaci",
	"EDITORIAL_DECLARATION": "Editorské prohlášení",
	"AUTORITY": "Vydavatelská instituce",
	"PUBLISHER": "Vydavatel",
	"PUBLICATION_PLACE": "Místo vydání",
	"DATE": "Datum",
	"AVAILABILITY": "Dostupnost",
	"TEXT_EDITION": "Textová edice",
	"EDITION": "Edice",
	"ENCODING_DESCRIPTION": "Popis kódování",
	"PROJECT_DESCRIPTION": "Popis projektu",
	"CORRECTIONS": "Opravy",
	"NORMALIZATION": "Normalizace",
	"SEGMENTATION": "Segmentace",
	"HYPHENATION": "Dělení slov",
	"SAMPLING_METHODS": "Vzorové metody",
	"PROFILE_DESCRIPTION": "Popis textu",
	"LANGUAGE": "Jazyk",
	"TEXT_DESCRIPTION": "Popis textu",
	"SETTING_DESCRIPTION": "Nastavení textu",
	"TEXT_CLASSIFICATION": "Klasifikace textu",
	"REVISIONS": "Revize",
	"MANUSCRIPT_CURRENT_LOCATION": "Místo uložení",
	"MANUSCRIPT_LOCATION": "Místo",
	"MANUSCRIPT_COLLECTION": "Sbírka",
	"MANUSCRIPT_CODE": "Signatura",
	"MANUSCRIPT_NAME": "Název",
	"MANUSCRIPT_CONTENTS": "Obsah",
	"MANUSCRIPT_CONTENT_SUMMARY": "Shrnutí obsahu",
	"MANUSCRIPT_ITEMS": "Texty",
	"INCIPIT": "Incipit",
	"EXPLICIT": "Explicit",
	"MANUSCRIPT_PHYSICAL_DESCRIPTION": "Fyzický popis",
	"MANUSCRIPT_SUPPORT": "Materiál",
	"EXTENT": "Rozsah",
	"COLLATION": "Kolace",
	"CONDITION": "Stav",
	"FOLIATION": "Foliace",
	"MANUSCRIPT_SUPPORT_DESCRIPTION": "Popis materiálu",
	"LAYOUT": "Rozložení",
	"OVERVIEW": "Přehled",
	"WRITING": "Písmo",
	"DECORATION": "Dekorace",
	"MANUSCRIPT_HISTORY": "Historie rukopisu",
	"SUMMARY": "Shrnutí",
	"ORIGIN": "Původ",
	"ACQUISITION": "Akvizice",
	"PROVENANCE": "Provenience",
	"ADDITIONAL_INFORMATION": "Další informace",
	"ADDITIONAL_MATERIALS": "Další materiály",
	"LIST_PERSON": "Osob",
	"LIST_PLACE": "Míst",
	"LIST_ORG": "Institucí",
	"LIST_TERM": "Slov",
	"LIST_GLOSS": "Lesků",
	"NO_ELEMENTS": "Žádné položky",
	"PAGE_MISSING": "(miss)",
	"PAGE_MISSING_RIGHT": " - (miss)",
	"PAGE_MISSING_LEFT": "(miss) - ",
	"GO_TO_TEXT": "Přejít na text",
	"OCCURRENCES": "výskyty",
	"OCCURRENCE": "výskyt",
	"NO_MATCHES_FOUND": "Nenalezena shoda",
	"DOCUMENTS": "Documenty",
	"DOCUMENT": "Document",
	"FOL": "Fol.",
	"DOC": "Dok.",
	"MULTI_SELECTION": "Vybrat vše",
	"ALL": "Všechno",
	"SHOWING_RESULTS_FOR_THE_WORD": "Zobrazeny výsledky pro výraz ",
	"SEARCH_FOR": "Hledaný výraz: ",
	"WE_HAVE_FOUND": "Počet nalezených výsledků: ",
	"ONE_RESULT": "1",
	"RESULTS": " ",
	"IN_THE": "v",
	"IN_THE_CURRENT_EDIION": "ve zvolené edici",
	"FOUND_IN": "nalezeno v dokumentu",
	"PAGE": "na straně",
	"LINE": "řádek",
	"PAR": "část",
	"NOTHING_FOUND": "Nic nenalezeno",
	"COMMON_WORDS_IGNORED": "Nelze vyhledat příliš častá slova",
	"SEARCH_TOO_SHORT": "Hledaný výraz je příliš krátký",
	"MORE_CHARACTER_ALERT": "Musí mít alespoň jedno písmeno",
	"SHOULD_BE": "Musí obsahovat alespoň",
	"CHARACTERS_OR_MORE": "písmena",

	"PERSNAME": "Osoby",
	"PLACENAME": "Místa",
	"ROLENAME": "Zaměstnání/role",
	"ORGNAME": "Instituce",
	"MEASURE": "Míry",
	"DATE": "Data",
	"TERM": "Období",
	"GLOSS": "Lesk",
	"clear": "Nevybráno",
	"multi": "Vybrat vše",
	"Multi selection": "Vybrat vše",

	"BIBLIO": "Bibliografie",
	"NO_REF": "Reference nenalezeny.",
	"TEXT_NOT_AVAILABLE": "Text zvoleného dokumentu není dostupný.",

	"VISIT_WEB_SITE": "Navštivte webové stránky projektu",
	"HELP": "Nápověda",
	"CLOSE": "Zavřít",
	// Shortcuts
	"KEYBOARD_SHORTCUTS": "Klávesové zkratky",
	"KS_OPEN_PROJECT_INFO": "Otevřít informace o projektu",
	"KS_SWITCH_MODE_VIEW": "Přepnout způsob zobrazení",
	"KS_GO_FULLSCREEN": "Celá obrazovka",
	"KS_OPEN_SEARCH": "Otevřít hledání",
	"KS_OPEN_PAGE_SELECTOR": "Zvolit stranu",
	"KS_OPEN_TEXT_SELECTOR": "Zvolit dokument",
	"KS_OPEN_EDITION_SELECTOR": "Zvolit druh edice",
	"KS_CHANGE_PAGE": "Posunout stranu",
	"KS_CHANGE_DOC": "Posunout dokument",

	"NEVER_SHOW_AGAIN": "Již nezobrazovat",

	"ERROR_LOADING_TEXT": "Nastal problém při načítání textu. Přepis textu této strany patrně ještě není k dispozici.",
	"ERROR_LOADING_IMAGE": "Nastal problém při načítání obrázku. Pro více informací prosím kontaktujte  kurátory.",
	"ERROR_LOADING_HI_IMAGE": "Nastal problém při načítání obrázků s vysokým rozlišením.",

	"NO_INFO": "Žádné informace",
	"NO_TRANSLATION_AVAILABLE": "Není k dispozici překlad.",

	"AFTER": "před",
	"BEFORE": "po",
	"FROM": "z",
	"TO": "do",
	"membership": "členství",

	"LIST_DOC": "Chronologický index",
	"ASCENDING_ORDER": "Vzestupně",
	"DESCENDING_ORDER": "Klesající",
	"SORT_ORDER": "Zvolte pořadí řazení",
	"SELECTOR_SORT_ATTRIBUTE": "Vyberte atribut řazení",
	"MORE": "zobrazit více",
	"LESS": "ukaž méně",

	"VERSES": "Verše",
	"PROSE": "Próza",

	"VISCOLL": "Viscoll",
	"SHOW_ALL_QUIRES": "Zobrazit všechny dotazy",
	"HIDE_ALL_QUIRES": "Skrýt všechny dotazy",

	"ENG": "Anglicky",
	"ITA": "Italský",
	"LAT": "Latina",
	"SPA": "Španělsky",
	"GUASCONE": "Gascon",

	"FOREIGN": "Cizí jazyk",
	"setting": "Setting",
	"entrance": "Entrance",
	"exit": "Exit",
	"business": "Business",
	"delivery": "Delivery",
	"modifier": "Modifier",
	"novelistic": "Novelistic",
	"mixed": "Mixed",

	"STAGE_SETTING_LABEL": "Setting",
	"STAGE_SETTING_DESC": "Popisuje nastavení",
	"STAGE_ENTRANCE_LABEL": "Entrance",
	"STAGE_ENTRANCE_DESC": "Popisuje vstup",
	"STAGE_EXIT_LABEL": "Exit",
	"STAGE_EXIT_DESC": "Popisuje exit",
	"STAGE_BUSINESS_LABEL": "Business",
	"STAGE_BUSINESS_DESC": "Popisuje činnost na jevišti",
	"STAGE_DELIVERY_LABEL": "Delivery",
	"STAGE_DELIVERY_DESC": "Popisuje způsob, jakým znak vypovídá",
	"STAGE_MODIFIER_LABEL": "Modifier",
	"STAGE_MODIFIER_DESC": "Poskytuje podrobnosti o znaku",
	"STAGE_NOVELISTIC_LABEL": "Novelistic",
	"STAGE_NOVELISTIC_DESC": "Narativní text určující směry scény",
	"STAGE_MIXED_LABEL": "Mixed",
	"STAGE_MIXED_DESC": "Více než jedna z popsaných hodnot",

	"NAMED_ENTITIES": "Pojmenované entity",
	"INTERESTING_ELEMENTS": "Zajímavé prvky",
	"STAGES": "Stage Directions",

	"LOADING_DATA": "Načítání dat ...",
	"EVT_INIT": "Inicializace EVT ...",
	"LOADING_STRUCTURE": "Načítání struktury ...",
	"PREPARING_EDITION_LEVELS": "Příprava úrovní vydání ...",
	"PREPARING_PAGE_PAIRS": "Příprava párů stránek ...",
	"PREPARING_TEXTS_PAGES": "Příprava textů a stránek ...",
	"PREPARING_UI": "Příprava uživatelského rozhraní ...",
	"PREPARING_MS_DESC": "Příprava popisu rukopisu ...",
	"PREPARING_TRANSLATION": "Příprava překladů ...",
	"PREPARING_FRONT_MATTER": "Příprava přední části ...",
	"PREPARING_LISTS": "Příprava seznamů ...",
	"PREPARING_BIBLIOGRAPHY": "Příprava bibliografie ...",
	"OPEN_DOCUMENT": "Otevřete dokument",
	"KENNING": "Kenning",
	
	"MEMBERS": "Členové",
	"LIST_ORG_FAMILIA": "Rodiny",
	"LIST_ORG_POPOLI": "Národy"
}
