jquery_lang_js.prototype.lang.en = {
	"DIPLOMATIC": "Diplomatic",
    "INTERPRETATIVE": "Interpretative",
   	"CRITICAL": "Critical",
    "TRANSLATION":"Translation",

    "MODE_SINGLE_TEXT": "Single Text Mode",
	"MODE_IMAGE_TEXT": "Image Text Mode",
	"MODE_TEXT_TEXT": "Text Text Mode",
	"MODE_BOOKREADER": "Bookreader mode",
	"PROJECT_INFO": "Project Info",
	"OPTIONS": "Options",
	"SETTINGS": "Settings",
	"LANGUAGES": "Languages",
	"ENGLISH": "English",
	"ITALIAN": "Italian",
	"FRENCH": "French",
	"GO_FULLSCREEN": "Go Fullscreen",
    "EXIT_FULLSCREEN": "Exit Fullscreen",
	"TOGGLE_MENU": "Toggle Menu",
	"PREVIOUS_PAGE": "Previous Page",
	"NEXT_PAGE": "Next Page",
	"EXPAND_FRAME": "Expand Frame",
	"COLLAPSE_FRAME": "Collapse Frame",
	"SELECTOR_PAGE": "Page selector",
	"SELECTOR_DOUBLE_PAGE": "Double page selector",
	"THUMBNAILS": "Thumbnails",
	"THUMBS": "Thumbs",
	"SELECTOR_EDITION_LEVEL": "Edition Level Selector",
	"REGESTO": "Regesto",
    "REGESTO_TITLE":"Click here to toggle Regesto",
	"INFORMATION_ABOUT_THIS_TEXT": "Information about this text",
	"INFO": "Info",
	"MAGNIFIER_LENS": "Magnifier Lens",
	"MAGNIFIER": "Magnifier",
	"HOT_SPOTS": "Hot Spots",
	"HOTSPOTS": "HotSpots",
	"IMAGE_TEXT_LINK": "Image Text Link",
	"IMAGE_TEXT": "Image-Text",
	"MANUSCRIPT_DESCRIPTION": "Manuscript description",
	"MS_DESC": "MS Desc",
	"TOGGLE_SEARCH": "Toggle search",
	"TOGGLE_KEYBOARD": "Toggle keyboard",
	"CLEAR_SEARCH": "Clear search",
	"START_SEARCH": "Start search",
	"ENTER_YOUR_QUERY_INTO_THE_SEARCH_BOX_ABOVE": "Enter your query into the search box above",
	"OPEN_SEARCH": "Open search",
	"SEARCH": "Search",
	"SELECTOR_ENTITIES": "Entities selector",
	"NO_SELECTION": "No selection",
	"SELECT_ALL": "Select All",
	"CLEAR_SELECTION": "Clear selection",
	"DECREASE_FONT_SIZE": "Decrease font size",
	"INCREASE_FONT_SIZE": "Increase font size",
	"PREVIOUS_DOCUMENT": "Previous document",
	"NEXT_DOCUMENT": "Next document",
	"100%": "100%",
	"FIT_TO_FRAME": "Fit to frame",
	"ZOOM_OUT": "Zoom out",
	"ZOOM_IN": "Zoom in",
	"NO_IMAGE": "No image",
	"EXPAND_FRAME": "Expand frame",
	"SELECTOR_TEXT": "Text selector",
	"TOGGLE_LISTS": "Toggle lists",
	"OPEN_LISTS": "Open Lists",
	"LISTS": "Lists",
	"EVT_INFORMATION": "EVT information",
	"GENERAL_INFORMATION": "General information",
	"TITLE": "Title of the edition",
	"TEXT_AUTHOR": "Text author",
	"PRINCIPAL_INVESTIGATOR": "Principal investigator",
  	"EDITION_STATEMENT": "Edition Statement",
  	"RESPONSIBILITY_STATEMENT": "Statement of responsibility",
	"PUBLICATION_INFORMATION": "Publication information",
	"EDITORIAL_DECLARATION": "Editorial declaration",
	"AUTORITY": "Release autority",
	"PUBLISHER": "Publisher",
	"PUBLICATION_PLACE": "Publication place",
	"DATE": "Date",
	"AVAILABILITY": "Availability",
	"TEXT_EDITION": "Text edition",
	"EDITION": "Edition",
	"ENCODING_DESCRIPTION": "Encoding description",
	"PROJECT_DESCRIPTION": "Project description",
	"CORRECTIONS": "Corrections",
	"NORMALIZATION": "Normalization",
	"SEGMENTATION": "Segmentation",
	"HYPHENATION": "Hyphenation",
	"SAMPLING_METHODS": "Sampling methods",
	"PROFILE_DESCRIPTION": "Profile description",
	"LANGUAGE": "Language",
	"TEXT_DESCRIPTION": "Text description",
	"SETTING_DESCRIPTION": "Text setting",
	"TEXT_CLASSIFICATION": "Text classification",
	"REVISIONS": "Revisions",
	"MANUSCRIPT_CURRENT_LOCATION": "Current location",
	"MANUSCRIPT_LOCATION": "Location",
	"MANUSCRIPT_COLLECTION": "Collection",
	"MANUSCRIPT_CODE": "Code",
	"MANUSCRIPT_NAME": "Name",
	"MANUSCRIPT_CONTENTS": "Contents",
	"MANUSCRIPT_CONTENT_SUMMARY": "Content summary",
	"MANUSCRIPT_ITEMS": "Items",
	"INCIPIT": "Incipit",
	"EXPLICIT": "Explicit",
	"MANUSCRIPT_PHYSICAL_DESCRIPTION": "Physical description",
	"MANUSCRIPT_SUPPORT": "Support",
	"EXTENT": "Extent",
	"COLLATION": "Collation",
	"CONDITION": "Condition",
	"FOLIATION": "Foliation",
	"MANUSCRIPT_SUPPORT_DESCRIPTION": "Support description",
	"LAYOUT": "Layout",
	"OVERVIEW": "Overview",
	"WRITING": "Writing",
	"DECORATION": "Decoration",
	"MANUSCRIPT_HISTORY": "Manuscript history",
	"SUMMARY": "Summary",
	"ORIGIN": "Origin",
	"ACQUISITION": "Acquisition",
	"PROVENANCE": "Provenance",
	"ADDITIONAL_INFORMATION": "Additional information",
	"ADDITIONAL_MATERIALS": "Additional materials",
	"LIST_PERSON": "List of persons",
	"LIST_PLACE": "List of places",
	"LIST_ORG": "List of organizations",
  	"LIST_TERM": "List of words",
  	"LIST_GLOSS": "List of glosses",
	"NO_ELEMENTS": "No elements",
    "PAGE_MISSING": "(miss)",
    "PAGE_MISSING_RIGHT": " - (miss)",
    "PAGE_MISSING_LEFT": "(miss) - ",
    "GO_TO_TEXT": "Go to Text",
    "OCCURRENCES": "occurrences",
    "OCCURRENCE": "occurrence",
    "NO_MATCHES_FOUND": "No matches found",
    "DOCUMENTS": "Documents",
    "DOCUMENT": "Document",
    "FOL": "Fol.",
    "DOC": "Doc.",
    "MULTI_SELECTION": "Multi selection",
    "ALL": "All",

    "SHOWING_RESULTS_FOR_THE_WORD": "Showing results for the word ",
    "SEARCH_FOR": "Search for ",
    "WE_HAVE_FOUND": "We have found ",
    "ONE_RESULT": "1 result",
    "RESULTS": "results",
    "IN_THE": "in the",
    "IN_THE_CURRENT_EDIION": "in the selected edition",
    "FOUND_IN": "found in",
    "PAGE": "page",
    "NOTHING_FOUND": "Nothing found.",
    "COMMON_WORDS_IGNORED": "Common words are largely ignored.",
    "SEARCH_TOO_SHORT": "Search too short",
    "MORE_CHARACTER_ALERT": "Should be one character or more.",
    "SHOULD_BE": "Should be",
    "CHARACTERS_OR_MORE": "characters or more.",

    "persName": "People",
    "placeName": "Places",
    "roleName": "Crafts/Roles",
    "orgName":"Religious organizations",
    "measure": "Currencies",
    "date": "Dates",
    "term": "Term",
    "gloss": "Gloss",
    "clear": "No selection",
    "multi": "Multi selection",
    "Multi selection": "Multi selection",

    "BIBLIO": "Bibliography",
    "NO_REF": "No reference found.",
    "TEXT_NOT_AVAILABLE": "The text for the selected document is not available.",

    "VISIT_WEB_SITE": "Visit the website of the project.",
    "HELP": "Help",
    "CLOSE": "Close",
    // Shortcuts
    "KEYBOARD_SHORTCUTS": "Keyboard shortcuts",
    "KS_OPEN_PROJECT_INFO" : "Open project info",
    "KS_SWITCH_MODE_VIEW" : "Switch mode view",
    "KS_GO_FULLSCREEN": "Go fullscreen",
    "KS_OPEN_SEARCH": "Open search",
    "KS_OPEN_PAGE_SELECTOR" : "Open page selector",
    "KS_OPEN_TEXT_SELECTOR" : "Open text selector",
    "KS_OPEN_EDITION_SELECTOR" : "Open edition selector",
    "KS_CHANGE_PAGE" : "Change page",
    "KS_CHANGE_DOC" : "Change document",

    "NEVER_SHOW_AGAIN" : "Never show again",

    "ERROR_LOADING_TEXT": "There was an error in loading the text. The transcript for this page may not yet be available. ",
    "ERROR_LOADING_IMAGE": "There was an error in loading the image. For more informations, please contact the curators.",
    "ERROR_LOADING_HI_IMAGE": "There was a problem while loading the hi-res image.",
    
    "NO_INFO": "No information",
    "NO_TRANSLATION_AVAILABLE": "No translation available.",
    
    "AFTER": "after",
    "BEFORE": "before",
    "FROM": "from",
    "TO": "to",
    "membership": "Membership",
	
	"LIST_DOC": "Chronological index",
	"ASCENDING_ORDER":"Ascending", 
	"DESCENDING_ORDER":"Descending",
	"SORT_ORDER":"Choose sorting order",
	"SELECTOR_SORT_ATTRIBUTE":"Choose sort attribute",
	"MORE":"show more",
    "LESS": "show less",

	"VERSES": "Verses",
	"PROSE": "Prose"
}

