jquery_lang_js.prototype.lang.fr = {
	"DIPLOMATIC": "Diplomatique",
    "INTERPRETATIVE": "Interprétatif",

    "MODE_SINGLE_TEXT": "Mode Texte",
	"MODE_IMAGE_TEXT": "Mode Image|Texte",
	"MODE_TEXT_TEXT": "Mode Texte|Texte",
	"MODE_BOOKREADER": "Mode Livre",
	"PROJECT_INFO": "Informations sur le project",
	"OPTIONS": "Options",
	"SETTINGS": "Impostations",
	"LANGUAGES": "Langues",
	"ENGLISH": "Anglais",
	"ITALIAN": "Italien",
	"FRENCH": "Français",
	"GO_FULLSCREEN": "Plein écran",
    "EXIT_FULLSCREEN": "Quitter plein écran",
	"TOGGLE_MENU": "Ouvrir/Fermer le menù",
	"PREVIOUS_PAGE": "Page précédente",
	"NEXT_PAGE": "Page suivante",
	"EXPAND_FRAME": "Agrandir le cadre",
	"COLLAPSE_FRAME": "Réduire le cadre",
	"SELECTOR_PAGE": "Sélecteur de page",
	"SELECTOR_DOUBLE_PAGE": "Sélecteur de pages doubles",
	"THUMBNAILS": "Miniatures",
	"THUMBS": "Miniatures",
	"SELECTOR_EDITION_LEVEL": "Sélecteur de niveau d'édition",
	"REGESTO": "Regesto",
    "REGESTO_TITLE":"Regesto",
	"INFORMATION_ABOUT_THIS_TEXT": "A propos de ce texte",
	"INFO": "Info",
	"MAGNIFIER_LENS": "Loupe",
	"MAGNIFIER": "Loupe",
	"HOT_SPOTS": "Les zones sensibles de l'image",
	"HOTSPOTS": "Hot Spots",
	"IMAGE_TEXT_LINK": "Lien Image-Texte",
	"IMAGE_TEXT": "Image Texte",
	"MANUSCRIPT_DESCRIPTION": "Description du manuscrit",
	"MS_DESC": "MS Desc",
	"TOGGLE_SEARCH": "Ouvrir/Fermer la recherche",
	"TOGGLE_KEYBOARD": "Ouvrir/Fermer le clavier",
	"CLEAR_SEARCH": "Réinitialiser la recherche",
	"START_SEARCH": "Lancer la recherche",
	"ENTER_YOUR_QUERY_INTO_THE_SEARCH_BOX_ABOVE": "Entrez la chaîne à rechercher!",
	"OPEN_SEARCH": "Ouvrir la recherche",
	"SEARCH": "Recherche",
	"SELECTOR_ENTITIES": "Sélecteur des entités",
	"NO_SELECTION": "Pas de sélection",
	"SELECT_ALL": "Sélectionner tous",
	"CLEAR_SELECTION": "Effacer la sélection",
	"DECREASE_FONT_SIZE": "Diminuer la taille du texte",
	"INCREASE_FONT_SIZE": "Augmenter la taille du texte",
	"PREVIOUS_DOCUMENT": "Document précédent",
	"NEXT_DOCUMENT": "Document suivant",
	"100%": "100%",
	"FIT_TO_FRAME": "Adapter",
	"ZOOM_OUT": "Agrandir",
	"ZOOM_IN": "Dézoomer",
	"NO_IMAGE": "Pas d'image",
	"EXPAND_FRAME": "Espandi",
	"SELECTOR_TEXT": "Sélecteur des textes",
	"TOGGLE_LISTS": "Ouvrir/Fermer les listes",
	"OPEN_LISTS": "Ouvrir les listes",
	"LISTS": "Listes",
	
	"TEXT_AUTHOR": "Auteur du texte",
	"PRINCIPAL_INVESTIGATOR": "Principal coordinateur",
	"PUBLICATION_INFORMATION": "Information sur la publication",
	"PUBLISHER": "Éditeur",
	"PUBLICATION_PLACE": "Lieu de publication",
	"DATE": "Date",
	"AVAILABILITY": "Disponibilité",
	"TEXT_EDITION": "Édition de texte",
	"EDITION": "Édition",
	"ENCODING_DESCRIPTION": "Description de codage",
	"PROJECT_DESCRIPTION": "Description du projet",
	"CORRECTIONS": "Corrections",
	"NORMALIZATION": "Normalisation",
	"SEGMENTATION": "Segmentation",
	"HYPHENATION": "Hyphenation",
	"SAMPLING_METHODS": "Les méthodes d'échantillonnage",
	"PROFILE_DESCRIPTION": "Description du texte",
	"LANGUAGE": "Langue",
	"TEXT_CLASSIFICATION": "Classification du texte",
	"REVISIONS": "Révisions",
	"MANUSCRIPT_CURRENT_LOCATION": "Lieu de conservation",
	"MANUSCRIPT_LOCATION": "Lieu",
	"MANUSCRIPT_COLLECTION": "Collection",
	"MANUSCRIPT_CODE": "Code",
	"MANUSCRIPT_NAME": "Nom",
	"MANUSCRIPT_CONTENTS": "Contenu",
	"MANUSCRIPT_CONTENT_SUMMARY": "Résumé",
	"MANUSCRIPT_ITEMS": "Textes",
	"INCIPIT": "Incipit",
	"EXPLICIT": "Explicit",
	"MANUSCRIPT_PHYSICAL_DESCRIPTION": "Description physique",
	"MANUSCRIPT_SUPPORT": "Soutien",
	"EXTENT": "Extent",
	"COLLATION": "Collation",
	"CONDITION": "État",
	"FOLIATION": "Foliation",
	"MANUSCRIPT_SUPPORT_DESCRIPTION": "Description de l'appui",
	"LAYOUT": "Disposition",
	"OVERVIEW": "Vue d'ensemble",
	"WRITING": "Écriture",
	"DECORATION": "Décoration",
	"MANUSCRIPT_HISTORY": "Histoire manuscrit",
	"SUMMARY": "Résumé",
	"ORIGIN": "Origine",
	"ACQUISITION": "Acquisition",
	"PROVENANCE": "Provenance",
	"ADDITIONAL_INFORMATION": "Information supplémentaire",
	"ADDITIONAL_MATERIALS": "Matériaux supplémentaires",
	"LIST_PERSON": "Liste des personnes",
	"LIST_PLACE": "Liste des lieux",
	"NO_ELEMENTS": "Rien",
    "PAGE_MISSING": "(miss)",
    "PAGE_MISSING_RIGHT": " - (miss)",
    "PAGE_MISSING_LEFT": "(miss) - ",
    "GO_TO_TEXT": "Aller au texte",
    "OCCURRENCES": "occurrences",
    "OCCURRENCE": "occurrence",
    "NO_MATCHES_FOUND": "Aucun résultat",
    "DOCUMENTS": "Documents",
    "DOCUMENT": "Document",
    "FOL": "Fol.",
    "DOC": "Doc.",
    "MULTI_SELECTION": "Sélection multiple",
    "SHOWING_RESULTS_FOR_THE_WORD": "Présentant les résultats le mot ",
    "SEARCH_FOR": "Rechercher ",
    "WE_HAVE_FOUND": "Nous avons trouvé ",
    "ONE_RESULT": "1 résultat",
    "RESULTS": "résultats",
    "IN_THE": "dans",
    "IN_THE_CURRENT_EDIION": "dans l'édition sélectionné",
    "FOUND_IN": "trouvé dans",
    "PAGE": "page",
    "NOTHING_FOUND": "Pas des résultats.",
    "COMMON_WORDS_IGNORED": "Les mots communs sont souvent ignorées.",
    "SEARCH_TOO_SHORT": "Mot recherché trop court.",
    "MORE_CHARACTER_ALERT": "Le mot de la recherche doit être plus long que un ou plusieurs caractères.",
    "SHOULD_BE": "Devrait être",
    "CHARACTERS_OR_MORE": "caractères ou plus.",

    "persName": "Gens",
    "placeName": "Lieux",
    "roleName": "Artisanat/Rôles",
    "measure": "Monnaies",
    "date": "Dates",
    "clear": "Pas de sélection",
	"multi": "Multi sélection",

    "BIBLIO": "Bibliographie",
    "NO_REF": "Aucune référence trouvée.",
    "TEXT_NOT_AVAILABLE": "Le texte du document sélectionné n'est pas disponible.",

    "VISIT_WEB_SITE": "Visitez le site Web du projet.",
    "HELP": "Help",
    "CLOSE": "Fermer",
    // Shortcuts
    "KEYBOARD_SHORTCUTS": "Les raccourcis clavier",
    "KS_OPEN_PROJECT_INFO" : "Ouvrir les informations sur le project",
    "KS_SWITCH_MODE_VIEW" : "Changer mode de visualization",
    "KS_GO_FULLSCREEN": "Plein écran",
    "KS_OPEN_SEARCH": "Ouvrir la recherche",
    "KS_OPEN_PAGE_SELECTOR" : "Ouvrir le selecteur des pages",
    "KS_OPEN_TEXT_SELECTOR" : "Ouvrir le selecteur des textes",
    "KS_OPEN_EDITION_SELECTOR" : "Ouvrir le selecteur de niveau d'édition",
    "KS_CHANGE_PAGE" : "Changer page",
    "KS_CHANGE_DOC" : "Changer document"

}
