jquery_lang_js.prototype.lang.it = {
	"DIPLOMATIC": "Diplomatica",
	"INTERPRETATIVE": "Interpretativa",
	"CRITICAL": "Critica",
	"TRANSLATION": "Traduzione",

	"MODE_SINGLE_TEXT": "Testo singolo",
	"MODE_IMAGE_TEXT": "Immagine-Testo",
	"MODE_TEXT_TEXT": "Testo-Testo",
	"MODE_BOOKREADER": "Sfoglia manoscritto",
	"PROJECT_INFO": "Informazioni sul progetto",
	"OPTIONS": "Opzioni",
	"SETTINGS": "Impostazioni",
	"LANGUAGES": "Lingue",
	"ENGLISH": "Inglese",
	"ITALIAN": "Italiano",
	"FRENCH": "Francese",
	"GERMAN": "Tedesco",
	"CZECH": "Ceco",
	"GO_FULLSCREEN": "Vai a schermo intero",
	"EXIT_FULLSCREEN": "Esci da schermo intero",
	"TOGGLE_MENU": "Apri/chiudi menu",
	"PREVIOUS_PAGE": "Pagina precedente",
	"NEXT_PAGE": "Pagina successiva",
	"EXPAND_FRAME": "Espandi",
	"COLLAPSE_FRAME": "Comprimi",
	"SELECTOR_PAGE": "Selettore di pagine",
	"SELECTOR_DOUBLE_PAGE": "Selettore di pagine",
	"THUMBNAILS": "Miniature",
	"THUMBS": "Miniature",
	"SELECTOR_EDITION_LEVEL": "Selettore livello edizione",
	"REGESTO": "Regesto",
	"REGESTO_TITLE": "Clicca qui per visualizzare il testo del documento o il relativo regesto",
	"INFORMATION_ABOUT_THIS_TEXT": "Informazioni su questo testo",
	"INFO": "Info",
	"MAGNIFIER_LENS": "Lente di ingrandimento",
	"MAGNIFIER": "Lente",
	"HOT_SPOTS": "Aree sensibili dell'immagine",
	"HOTSPOTS": "Hot Spots",
	"IMAGE_TEXT_LINK": "Collegamento Immagine Testo",
	"IMAGE_TEXT": "Immagine Testo",
	"MANUSCRIPT_DESCRIPTION": "Descrizione del manoscritto",
	"MS_DESC": "MS Desc",
	"TOGGLE_SEARCH": "Apri/chiudi Ricerca",
	"TOGGLE_KEYBOARD": "Apri/chiudi tastiera",
	"CLEAR_SEARCH": "Pulisci ricerca",
	"START_SEARCH": "Avvia ricerca",
	"ENTER_YOUR_QUERY_INTO_THE_SEARCH_BOX_ABOVE": "Inserire la stringa da cercare!",
	"OPEN_SEARCH": "Apri ricerca",
	"SEARCH": "Ricerca",
	"SELECTOR_ENTITIES": "Evidenzia le entità presenti nel testo",
	"NO_SELECTION": "Nessuna selezione",
	"SELECT_ALL": "Seleziona tutti",
	"CLEAR_SELECTION": "Pulisci selezione",
	"DECREASE_FONT_SIZE": "Diminuisci le dimensioni del testo",
	"INCREASE_FONT_SIZE": "Aumenta le dimensioni del testo",
	"PREVIOUS_DOCUMENT": "Documento precedente",
	"NEXT_DOCUMENT": "Documento successivo",
	"100%": "100%",
	"FIT_TO_FRAME": "Adatta",
	"ZOOM_OUT": "Aumenta zoom",
	"ZOOM_IN": "Diminuisci zoom",
	"NO_IMAGE": "Nessuna immagine",
	"EXPAND_FRAME": "Espandi",
	"SELECTOR_TEXT": "Selettore di testi",
	"TOGGLE_LISTS": "Apri/chiudi Liste",
	"OPEN_LISTS": "Apri Liste",
	"LISTS": "Liste",

	"EVT_INFORMATION": "Informazioni su EVT",
	"GENERAL_INFORMATION": "Informazioni generali",
	"TITLE": "Titolo dell'edizione",
	"TEXT_AUTHOR": "Autore del testo",
	"PRINCIPAL_INVESTIGATOR": "Coordinatore principale",
	"EDITION_STATEMENT": "Dichiarazione dell'edizione",
	"RESPONSIBILITY_STATEMENT": "Dichiarazione di responsabilità",
	"PUBLICATION_INFORMATION": "Informazioni sulla pubblicazione",
	"EDITORIAL_DECLARATION": "Dichiarazione editoriale ",
	"AUTORITY": "Autorità di pubblicazione",
	"PUBLISHER": "Editore",
	"PUBLICATION_PLACE": "Luogo di pubblicazione",
	"DATE": "Data",
	"AVAILABILITY": "Disponibilità",
	"TEXT_EDITION": "Edizione del testo",
	"EDITION": "Edizione",
	"ENCODING_DESCRIPTION": "Descrizione della codifica",
	"PROJECT_DESCRIPTION": "Descrizione del progetto",
	"CORRECTIONS": "Correzioni",
	"NORMALIZATION": "Normalizzazione",
	"SEGMENTATION": "Segmentazione",
	"HYPHENATION": "Sillabazione",
	"SAMPLING_METHODS": "Metodi di campionamento",
	"PROFILE_DESCRIPTION": "Descrizione del testo",
	"LANGUAGE": "Lingua",
	"TEXT_DESCRIPTION": "Descrizione del testo",
	"SETTING_DESCRIPTION": "Impostazione del testo",
	"TEXT_CLASSIFICATION": "Classificazione del testo",
	"REVISIONS": "Revisioni",
	"MANUSCRIPT_CURRENT_LOCATION": "Luogo di conservazione",
	"MANUSCRIPT_LOCATION": "Luogo",
	"MANUSCRIPT_COLLECTION": "Collezione",
	"MANUSCRIPT_CODE": "Codice",
	"MANUSCRIPT_NAME": "Nome",
	"MANUSCRIPT_CONTENTS": "Contenuti",
	"MANUSCRIPT_CONTENT_SUMMARY": "Riassunto",
	"MANUSCRIPT_ITEMS": "Testi",
	"INCIPIT": "Incipit",
	"EXPLICIT": "Explicit",
	"MANUSCRIPT_PHYSICAL_DESCRIPTION": "Descrizione fisica",
	"MANUSCRIPT_SUPPORT": "Supporto",
	"EXTENT": "Extent",
	"COLLATION": "Collazione",
	"CONDITION": "Condizione",
	"FOLIATION": "Numerazione pagine",
	"MANUSCRIPT_SUPPORT_DESCRIPTION": "Descrizione del supporto",
	"LAYOUT": "Impaginazione",
	"OVERVIEW": "Panoramica",
	"WRITING": "Scrittura",
	"DECORATION": "Ornamenti",
	"MANUSCRIPT_HISTORY": "Storia del manoscritto",
	"SUMMARY": "Riassunto",
	"ORIGIN": "Origine",
	"ACQUISITION": "Acquisizione",
	"PROVENANCE": "Provenienza",
	"ADDITIONAL_INFORMATION": "Informazioni aggiuntive",
	"ADDITIONAL_MATERIALS": "Materiali aggiuntivi",
	"LIST_PERSON": "Lista delle persone",
	"LIST_PLACE": "Lista dei luoghi",
	"LIST_ORG": "Lista di enti",
	"LIST_TERM": "Lista di parole",
	"LIST_GLOSS": "Lista di glosse",
	"NO_ELEMENTS": "Nessun elemento",
	"PAGE_MISSING": "(miss)",
	"PAGE_MISSING_RIGHT": " - (miss)",
	"PAGE_MISSING_LEFT": "(miss) - ",
	"GO_TO_TEXT": "Vai al testo",
	"OCCURRENCES": "occorrenze",
	"OCCURRENCE": "occorrenza",
	"NO_MATCHES_FOUND": "Nessun risultato trovato",
	"DOCUMENTS": "Documenti",
	"DOCUMENT": "Documento",
	"FOL": "Fol.",
	"DOC": "Doc.",
	"ALL": "Tutti",

	"MULTI_SELECTION": "Selezione multipla",
	"SHOWING_RESULTS_FOR_THE_WORD": "Di seguito i risultati per ",
	"SEARCH_FOR": "Ricerca di ",
	"WE_HAVE_FOUND": "Abbiamo trovato ",
	"ONE_RESULT": "1 risultato",
	"RESULTS": "risultati",
	"IN_THE": "in",
	"IN_THE_CURRENT_EDIION": "nell'edizione selezionata",
	"FOUND_IN": "trovato in",
	"PAGE": "pagina",
	"NOTHING_FOUND": "Nessun risultato.",
	"COMMON_WORDS_IGNORED": "Le parole comuni sono spesso ignorate.",
	"SEARCH_TOO_SHORT": "Stringa ricercata troppo breve.",
	"MORE_CHARACTER_ALERT": "La stringa ricercata deve essere più lunga di uno o più caratteri.",
	"SHOULD_BE": "Dovrebbe essere ",
	"CHARACTERS_OR_MORE": "caratteri minimo.",

	"persName": "Persone",
	"placeName": "Luoghi",
	"roleName": "Mestieri/Ruoli",
	"orgName": "Enti religiosi",
	"measure": "Monete",
	"date": "Date",
	"term": "Term",
	"gloss": "Gloss",
	"clear": "Nessuna selezione",
	"multi": "Selezione multipla",

	"BIBLIO": "Bibliografia",
	"NO_REF": "Nessun riferimento trovato.",
	"TEXT_NOT_AVAILABLE": "Il testo del documento selezionato non è ancora disponibile.",

	"VISIT_WEB_SITE": "Visita il sito web del progetto.",
	"HELP": "Aiuto",
	"CLOSE": "Chiudi",

	// Shortcuts
	"KEYBOARD_SHORTCUTS": "Scorciatoie da tastiera",
	"KS_OPEN_PROJECT_INFO": "Apertura informazioni sul progetto",
	"KS_SWITCH_MODE_VIEW": "Cambio vista",
	"KS_GO_FULLSCREEN": "Schermo intero",
	"KS_OPEN_SEARCH": "Apertura ricerca",
	"KS_OPEN_PAGE_SELECTOR": "Apertura selettore pagine",
	"KS_OPEN_TEXT_SELECTOR": "Apertura selettore testi",
	"KS_OPEN_EDITION_SELECTOR": "Apertura selettore livelli di edizione",
	"KS_CHANGE_PAGE": "Cambio pagina",
	"KS_CHANGE_DOC": "Cambio documento",

	"NEVER_SHOW_AGAIN": "Non mostrare più",

	"ERROR_LOADING_TEXT": "Si è verificato un errore nel caricamento del testo. La trascrizione per questa pagina potrebbe non essere disponibile. Per ulteriori informazioni contattare i curatori dell'edizione.",
	"ERROR_LOADING_IMAGE": "Si è verificato un errore durante il caricamento dell'immagine.",
	"ERROR_LOADING_HI_IMAGE": "Si è verificato un errore durante il caricamento dell'immagine ad alta risoluzione.",

	"NO_INFO": "Nessuna informazione",
	"NO_TRANSLATION_AVAILABLE": "Nessuna traduzione disponibile.",
	"AFTER": "dopo il",
	"BEFORE": "prima del",
	"FROM": "dal",
	"TO": "al",
	"membership": "Membri",

	"LIST_DOC": "Indice cronologico",
	"SELECTOR_SORT_ATTRIBUTE": "Scegli parametro di ordinamento",
	"SORT_ORDER": "Scegli modalità di ordinamento",
	"ASCENDING_ORDER": "Ascendente",
	"DESCENDING_ORDER": "Discendente",
	"MORE": "espandi",
	"LESS": "riduci",

	"VERSES": "Versi",
	"PROSE": "Prosa",

	"VISCOLL": "Viscoll",

	"ITA": "Italiano",
	"LAT": "Latino",
	"SPA": "Spagnolo",
	"GUASCONE": "Guascone",

	"foreign": "Lingua straniera",
	"setting": "Setting",
	"entrance": "Entrance",
	"exit": "Exit",
	"business": "Business",
	"delivery": "Delivery",
	"modifier": "Modifier",
	"novelistic": "Novelistic",
	"mixed": "Mixed",

	"STAGE_SETTING_LABEL": "Setting",
	"STAGE_SETTING_DESC": "Descrive l'ambientazione",
	"STAGE_ENTRANCE_LABEL": "Entrance",
	"STAGE_ENTRANCE_DESC": "Descrive un ingresso",
	"STAGE_EXIT_LABEL": "Exit",
	"STAGE_EXIT_DESC": "Descrive un'uscita",
	"STAGE_BUSINESS_LABEL": "Business",
	"STAGE_BUSINESS_DESC": "Descrive l'attività sul palco",
	"STAGE_DELIVERY_LABEL": "Delivery",
	"STAGE_DELIVERY_DESC": "Descrive il modo in cui un personaggio parla",
	"STAGE_MODIFIER_LABEL": "Modifier",
	"STAGE_MODIFIER_DESC": "Fornisce dettagli sul personaggio",
	"STAGE_NOVELISTIC_LABEL": "Novelistic",
	"STAGE_NOVELISTIC_DESC": "Testo narrativo che indica le direzioni di scena",
	"STAGE_MIXED_LABEL": "Mixed",
	"STAGE_MIXED_DESC": "Più di uno dei valori descritti",

	"NAMED_ENTITIES": "Entità Nominate",
	"INTERESTING_ELEMENTS": "Elementi interessanti",
	"STAGES": "Direttive di scena",

	"LOADING_DATA": "Caricamento dati...",
	"EVT_INIT": "Inizializzazione EVT...",
	"LOADING_STRUCTURE": "Caricamento struttura...",
	"PREPARING_EDITION_LEVELS": "Preparazione livelli di edizione...",
	"PREPARING_PAGE_PAIRS": "Preparazione coppie di pagine...",
	"PREPARING_TEXTS_PAGES": "Preparazione testi e pagine...",
	"PREPARING_UI": "Preparazione interfaccia ...",
	"PREPARING_MS_DESC": "Preparazione dettagli manoscritto...",
	"PREPARING_TRANSLATION": "Preparazione traduzioni...",
	"PREPARING_FRONT_MATTER": "Preparazione informazioni sul testo...",
	"PREPARING_LISTS": "Preparazione liste...",
	"PREPARING_BIBLIOGRAPHY": "Preparazione bibliografia...",
	"OPEN_DOCUMENT": "Apri documento"
}
