jquery_lang_js.prototype.lang.it = {
	"MODE_SINGLE_TEXT": "Modalità Testo singolo",
	"MODE_IMAGE_TEXT": "Modalità Testo Immagine",
	"MODE_TEXT_TEXT": "Modalità Testo Testo",
	"MODE_BOOKREADER": "Modalità Libro",
	"PROJECT_INFO": "Informazioni sul progetto",
	"OPTIONS": "Opzioni",
	"SETTINGS": "Impostazioni",
	"LANGUAGES": "Lingue",
	"ENGLISH": "Inglese",
	"ITALIAN": "Italiano",
	"FRENCH": "Francese",
	"GO_FULLSCREEN": "Vai a schermo intero",
    "EXIT_FULLSCREEN": "Esci da schermo intero",
	"TOGGLE_MENU": "Apri/chiudi menu",
	"PREVIOUS_PAGE": "Pagina precedente",
	"NEXT_PAGE": "Pagina successiva",
	"EXPAND_FRAME": "Espandi",
	"COLLAPSE_FRAME": "Comprimi",
	"SELECTOR_PAGE": "Selettore di pagine",
	"SELECTOR_DOUBLE_PAGE": "Selettore di pagine",
	"THUMBNAILS": "Miniature",
	"THUMBS": "Miniature",
	"SELECTOR_EDITION_LEVEL": "Selettore livello edizione",
	"REGESTO": "Regesto",
	"INFORMATION_ABOUT_THIS_TEXT": "Informazioni su questo testo",
	"INFO": "Info",
	"MAGNIFIER_LENS": "Lente di ingrandimento",
	"MAGNIFIER": "Lente",
	"HOT_SPOTS": "Aree sensibili dell'immagine",
	"HOTSPOTS": "Hot Spots",
	"IMAGE_TEXT_LINK": "Collegamento Immagine Testo",
	"IMAGE_TEXT": "Immagine Testo",
	"MANUSCRIPT_DESCRIPTION": "Descrizione del manoscritto",
	"MS_DESC": "MS Desc",
	"TOGGLE_SEARCH": "Apri/chiudi Ricerca",
	"TOGGLE_KEYBOARD": "Apri/chiudi tastiera",
	"CLEAR_SEARCH": "Pulisci ricerca",
	"START_SEARCH": "Avvia ricerca",
	"ENTER_YOUR_QUERY_INTO_THE_SEARCH_BOX_ABOVE": "Inserire la stringa da cercare!",
	"OPEN_SEARCH": "Apri ricerca",
	"SEARCH": "Ricerca",
	"SELECTOR_ENTITIES": "Selettore di entità",
	"NO_SELECTION": "Nessuna selezione",
	"SELECT_ALL": "Seleziona tutti",
	"CLEAR_SELECTION": "Pulisci selezione",
	"DECREASE_FONT_SIZE": "Diminuisci le dimensioni del testo",
	"INCREASE_FONT_SIZE": "Aumenta le dimensioni del testo",
	"PREVIOUS_DOCUMENT": "Documento precedente",
	"NEXT_DOCUMENT": "Documento successivo",
	"100%": "100%",
	"FIT_TO_FRAME": "Adatta",
	"ZOOM_OUT": "Aumenta zoom",
	"ZOOM_IN": "Diminuisci zoom",
	"NO_IMAGE": "Nessuna immagine",
	"EXPAND_FRAME": "Espandi",
	"SELECTOR_TEXT": "Selettore di testi",
	"TOGGLE_LISTS": "Apri/chiudi Liste",
	"OPEN_LISTS": "Apri Liste",
	"LISTS": "Liste",
	
	"TEXT_AUTHOR": "Autore del testo",
	"PRINCIPAL_INVESTIGATOR": "Coordinatore principale",
	"PUBLICATION_INFORMATION": "Informazioni sulla pubblicazione",
	"PUBLISHER": "Editore",
	"PUBLICATION_PLACE": "Luogo di pubblicazione",
	"DATE": "Data",
	"AVAILABILITY": "Disponibilità",
	"TEXT_EDITION": "Edizione del testo",
	"EDITION": "Edizione",
	"ENCODING_DESCRIPTION": "Descrizione della codifica",
	"PROJECT_DESCRIPTION": "Descrizione del progetto",
	"CORRECTIONS": "Correzioni",
	"NORMALIZATION": "Normalizzazione",
	"SEGMENTATION": "Segmentazione",
	"HYPHENATION": "Sillabazione",
	"SAMPLING_METHODS": "Metodi di campionamento",
	"PROFILE_DESCRIPTION": "Descrizione del testo",
	"LANGUAGE": "Lingua",
	"TEXT_CLASSIFICATION": "Classificazione del testo",
	"REVISIONS": "Revisioni",
	"MANUSCRIPT_CURRENT_LOCATION": "Luogo di conservazione",
	"MANUSCRIPT_LOCATION": "Luogo",
	"MANUSCRIPT_COLLECTION": "Collezione",
	"MANUSCRIPT_CODE": "Codice",
	"MANUSCRIPT_NAME": "Nome",
	"MANUSCRIPT_CONTENTS": "Contenuti",
	"MANUSCRIPT_CONTENT_SUMMARY": "Riassunto",
	"MANUSCRIPT_ITEMS": "Testi",
	"INCIPIT": "Incipit",
	"EXPLICIT": "Explicit",
	"MANUSCRIPT_PHYSICAL_DESCRIPTION": "Descrizione fisica",
	"MANUSCRIPT_SUPPORT": "Supporto",
	"EXTENT": "Extent",
	"COLLATION": "Collazione",
	"CONDITION": "Condizione",
	"FOLIATION": "Numerazione pagine",
	"MANUSCRIPT_SUPPORT_DESCRIPTION": "Descrizione del supporto",
	"LAYOUT": "Impaginazione",
	"OVERVIEW": "Panoramica",
	"WRITING": "Scrittura",
	"DECORATION": "Ornamenti",
	"MANUSCRIPT_HISTORY": "Storia del manoscritto",
	"SUMMARY": "Riassunto",
	"ORIGIN": "Origine",
	"ACQUISITION": "Acquisizione",
	"PROVENANCE": "Provenienza",
	"ADDITIONAL_INFORMATION": "Informazioni aggiuntive",
	"ADDITIONAL_MATERIALS": "Materiali aggiuntivi",
	"LIST_PERSON": "Lista delle persone",
	"LIST_PLACE": "Lista dei luoghi",
	"NO_ELEMENTS": "Nessun elemento.",
    "PAGE_MISSING": "miss",
    "GO_TO_TEXT": "Vai al testo",
    "OCCURRENCES": "occorrenze",
    "OCCURRENCE": "occorrenza",
    "NO_MATCHES_FOUND": "Nessun risultato trovato",
    "DOCUMENTS": "Documenti",
    "DOCUMENT": "Documento",
    "FOL": "Fol.",
    "DOC": "Doc.",
    "MULTI_SELECTION": "Selezione multipla",
    "SHOWING_RESULTS_FOR_THE_WORD": "Di seguito i risultati per ",
    "SEARCH_FOR": "Ricerca di ",
    "WE_HAVE_FOUND": "Abbiamo trovato ",
    "ONE_RESULT": "1 risultato",
    "RESULTS": "risultati",
    "IN_THE": "in",
    "IN_THE_CURRENT_EDIION": "nell'edizione selezionata",
    "FOUND_IN": "trovato in",
    "PAGE": "pagina",
    "NOTHING_FOUND": "Nessun risultato.",
    "COMMON_WORDS_IGNORED": "Le parole comuni sono spesso ignorate.",
    "SEARCH_TOO_SHORT": "Stringa ricercata troppo breve.",
    "MORE_CHARACTER_ALERT": "La stringa ricercata deve essere più lunga di uno o più caratteri.",
    "SHOULD_BE": "Dovrebbe essere ",
    "CHARACTERS_OR_MORE": "caratteri minimo.",

    "persName": "Persone",
    "placeName": "Luoghi",
    "roleName": "Mestieri/Ruoli",
    "measure": "Monete",
    "date": "Date",
    "clear": "Nessuna selezione",
    "multi": "Selezione multipla"
}

